name: "Changelog entry"
on:
  pull_request:
    # The specific activity types are listed here to include "labeled" and "unlabeled"
    # (which are not included by default for the "pull_request" trigger).
    # This is needed to allow skipping enforcement of the changelog in PRs with specific labels,
    # as defined in the (optional) "skipLabels" property.
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  # Enforces the addition of a changelog entry (a file in the .github/changelog directory) every pull request.
  changelog:
    runs-on: ubuntu-latest
    steps:
      # Allow skipping the changelog if the PR includes the label "Skip Changelog".
      - name: "Check for Skip Changelog label"
        id: hasSkipLabel
        uses: actions/github-script@v7
        with:
          script: |
            const { payload : { pull_request : { number, labels } } } = context;
            const skipLabel = 'Skip Changelog';
            const prLabels = labels.map( label => label.name );
            const hasSkipLabel = prLabels.includes( skipLabel );

            if ( hasSkipLabel ) {
              core.info( `Skipping changelog requirement for this PR (#${ number } because of the "${ skipLabel }" label.` );
            }
            core.setOutput( 'hasSkipLabel', hasSkipLabel.toString() );

      # Check if the PR includes a new added file in the .github/changelog directory.
      - name: "Check if the PR includes a new added file in the .github/changelog directory"
        uses: actions/github-script@v7
        with:
            script: |
                const { repo: { owner, repo }, payload : { pull_request : { number } } } = context;

                core.debug( `Changelogg check: Get list of files modified in ${ owner }/${ repo } #${ number }.` );
                const fileList = [];
                for await ( const response of github.paginate.iterator( github.rest.pulls.listFiles, {
                    owner,
                    repo,
                    pull_number: +number,
                    per_page: 100,
                } ) ) {
                    for ( const file of response.data ) {
                        fileList.push( file.filename );
                        if ( file.previous_filename ) {
                            fileList.push( file.previous_filename );
                        }
                    }
                }

                const changelogDir = '.github/changelog';
                const hasNewChangelogFile = fileList.some( file => {
                    core.debug( `Checking file: ${ file }` );
                    if ( file.startsWith( changelogDir ) ) {
                        core.info( `Found new changelog file: ${ file }` );
                        return true;
                    }
                    return false;
                } );
                
                if ( hasNewChangelogFile ) {
                    core.info( `PR #${ number } includes a new changelog file.` );
                } else {
                    core.info( `PR #${ number } does not include a new changelog file.` );
                    core.setFailed( `PR #${ number } does not include a new changelog file.` );
                }
                
                
        
    
        

